### ISSUE TITLE
robot_state_publisher instance inside CommunicationInterfaceROS causes segfault

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/XBotCore#16]
As you are already aware, on a clean 16.04 + xeno 3 installation I have a segfault on the instantiation of a ROS robot_state_publisher.
It is not easy to debug the error, but removing the robot state publisher for the core can be an option as (@EnricoMingo) was mentioning.

@alaurenzi @pepperig ideas?

**Comment by alaurenzi** [comment]
I would not like to sacrifice the usability of the framework (only one terminal to use it). We can use an external rs publisher only if we manage to launch everything from one terminal (e.g. roslaunch).

We really should understand what is behind this very strange segmentation fault, because it will happen again for sure, and maybe the next time it will affect a vital component of the system.

**Comment by alaurenzi** [comment]
If I understand correctly, in the latest master we don't have the integrated RS publisher anymore. Is this correct?

**Comment by liesrock** [comment]
@alaurenzi can you update us in this?

**Comment by alaurenzi** [comment]
Latest XBotCore devel contains an internal robot state publisher that looks to solve the problem

**Comment by liesrock** [comment]
I confirm that in this way the problem is solved: ok in devel I will merge it in master ASAP
